service: riot-service

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  stage: dev
  namespace: riot-1-point-0
  environment:
    REAGUE_LAMBDA_NAME: ${self:service}-${self:provider.stage}-reague
    SUMMONERS_TABLE: ${self:provider.namespace}-summonersTable
    SLACK_WEBHOOK: ${self:custom.envFile.slackWebhook}
    RIOT_API_KEY: ${self:custom.envFile.riotApiKey}
    RIOT_API_URL: ${self:custom.envFile.riotApiUrl}

custom:
  envFile: ${file(./environments/${self:provider.stage}.yml)}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  include:
    - src/**
    - node_modules/**
  exclude:
    - .gitignore
    - .git/**
    - package-lock.json

functions: ${file(./sls-functions/functions.yml)}

resources: ${file(./sls-resources/resources.yml)}

plugins:
  - serverless-iam-roles-per-function
  - serverless-webpack